version: '3.8'

services:
  statuspage-django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./statuspage:/opt/status-page/statuspage
    ports:
      - "8001:8001"

  statuspage-nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - statuspage-django
